function(get_pico_uart_port TX_PIN_IN PICO_UART_PORT_OUT)
    if(TX_PIN_IN EQUAL 0 OR TX_PIN_IN EQUAL 12 OR TX_PIN_IN EQUAL 16)
        set(${PICO_UART_PORT_OUT} 0 PARENT_SCOPE)
    elseif(TX_PIN_IN EQUAL 4 OR TX_PIN_IN EQUAL 8)
        set(${PICO_UART_PORT_OUT} 1 PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Invalid TX pin for Pico UART")
    endif()
endfunction()