#ifndef INPUTMODES_H_
#define INPUTMODES_H_

enum InputMode
{
    INPUT_MODE_XINPUT = 0x01,
    INPUT_MODE_SWITCH = 0x02,
    INPUT_MODE_HID = 0x03,
    INPUT_MODE_PSCLASSIC = 0x04,
    INPUT_MODE_XBOXORIGINAL = 0x05,
    INPUT_MODE_USBSERIAL = 0x06,
    INPUT_MODE_UART_BRIDGE = 0x07,
};

#endif // INPUTMODES_H_