/* Reference only — firmware does not include this header (hidraw XOR bytes 16–17 drift with IMU).
 * Autogenerated from Nintendo_Switch_2_Pro_Controller_20260324_063034.txt
 * Sparse (idx, mask, val): for each changed byte i in [2,20], mask = baseline^active,
 * val = active[i] & mask. Match: (report[i] & mask) == val for all tuples.
 * Regenerate: Tools/controller_capture (same JSON extraction as Switch2ProCaptureTables). */
#pragma once
#include <cstdint>

namespace Switch2ProCapture {

enum class Btn : uint8_t {
    FACE_B = 0,
    FACE_A = 1,
    FACE_Y = 2,
    FACE_X = 3,
    SHOULDER_R = 4,
    TRIGGER_ZR = 5,
    SHOULDER_L = 6,
    TRIGGER_ZL = 7,
    CENTER_MINUS = 8,
    CENTER_PLUS = 9,
    CENTER_HOME = 10,
    CENTER_CAPTURE = 11,
    DPAD_UP = 12,
    DPAD_DOWN = 13,
    DPAD_LEFT = 14,
    DPAD_RIGHT = 15,
    STICK_L3 = 16,
    STICK_R3 = 17,
    COUNT
};

static constexpr uint8_t CAPTURE_BYTE_LO = 2;
static constexpr uint8_t CAPTURE_BYTE_HI = 20;

static constexpr uint8_t FACE_B_N = 4;
static constexpr uint8_t FACE_B_IDX[4] = {7, 9, 16, 17};
static constexpr uint8_t FACE_B_MASK[4] = {0x70, 0x07, 0x62, 0x05};
static constexpr uint8_t FACE_B_VAL[4] = {0x40, 0x03, 0x20, 0x04};

static constexpr uint8_t FACE_A_N = 3;
static constexpr uint8_t FACE_A_IDX[3] = {6, 16, 17};
static constexpr uint8_t FACE_A_MASK[3] = {0x01, 0xd5, 0x02};
static constexpr uint8_t FACE_A_VAL[3] = {0x01, 0x10, 0x00};

static constexpr uint8_t FACE_Y_N = 3;
static constexpr uint8_t FACE_Y_IDX[3] = {6, 16, 17};
static constexpr uint8_t FACE_Y_MASK[3] = {0x01, 0xb3, 0x7f};
static constexpr uint8_t FACE_Y_VAL[3] = {0x00, 0x33, 0x3d};

static constexpr uint8_t FACE_X_N = 5;
static constexpr uint8_t FACE_X_IDX[5] = {6, 9, 10, 16, 17};
static constexpr uint8_t FACE_X_MASK[5] = {0x01, 0x07, 0x70, 0xd4, 0x07};
static constexpr uint8_t FACE_X_VAL[5] = {0x00, 0x04, 0x40, 0x94, 0x06};

static constexpr uint8_t SHOULDER_R_N = 4;
static constexpr uint8_t SHOULDER_R_IDX[4] = {6, 10, 16, 17};
static constexpr uint8_t SHOULDER_R_MASK[4] = {0x01, 0x70, 0x43, 0x07};
static constexpr uint8_t SHOULDER_R_VAL[4] = {0x00, 0x30, 0x02, 0x07};

static constexpr uint8_t TRIGGER_ZR_N = 4;
static constexpr uint8_t TRIGGER_ZR_IDX[4] = {6, 10, 16, 17};
static constexpr uint8_t TRIGGER_ZR_MASK[4] = {0x01, 0x70, 0xcb, 0x09};
static constexpr uint8_t TRIGGER_ZR_VAL[4] = {0x00, 0x40, 0x02, 0x09};

static constexpr uint8_t SHOULDER_L_N = 3;
static constexpr uint8_t SHOULDER_L_IDX[3] = {6, 16, 17};
static constexpr uint8_t SHOULDER_L_MASK[3] = {0x01, 0x38, 0x75};
static constexpr uint8_t SHOULDER_L_VAL[3] = {0x01, 0x08, 0x35};

static constexpr uint8_t TRIGGER_ZL_N = 3;
static constexpr uint8_t TRIGGER_ZL_IDX[3] = {6, 16, 17};
static constexpr uint8_t TRIGGER_ZL_MASK[3] = {0x01, 0x3a, 0x0a};
static constexpr uint8_t TRIGGER_ZL_VAL[3] = {0x01, 0x3a, 0x00};

static constexpr uint8_t CENTER_MINUS_N = 6;
static constexpr uint8_t CENTER_MINUS_IDX[6] = {6, 7, 9, 10, 16, 17};
static constexpr uint8_t CENTER_MINUS_MASK[6] = {0x01, 0x70, 0x07, 0x70, 0x92, 0x77};
static constexpr uint8_t CENTER_MINUS_VAL[6] = {0x00, 0x30, 0x04, 0x30, 0x80, 0x36};

static constexpr uint8_t CENTER_PLUS_N = 4;
static constexpr uint8_t CENTER_PLUS_IDX[4] = {6, 7, 16, 17};
static constexpr uint8_t CENTER_PLUS_MASK[4] = {0x01, 0x70, 0xbc, 0x08};
static constexpr uint8_t CENTER_PLUS_VAL[4] = {0x00, 0x30, 0xb4, 0x00};

static constexpr uint8_t CENTER_HOME_N = 3;
static constexpr uint8_t CENTER_HOME_IDX[3] = {9, 16, 17};
static constexpr uint8_t CENTER_HOME_MASK[3] = {0x07, 0x37, 0x0b};
static constexpr uint8_t CENTER_HOME_VAL[3] = {0x03, 0x36, 0x08};

static constexpr uint8_t CENTER_CAPTURE_N = 5;
static constexpr uint8_t CENTER_CAPTURE_IDX[5] = {6, 9, 10, 16, 17};
static constexpr uint8_t CENTER_CAPTURE_MASK[5] = {0x12, 0x07, 0x10, 0x0d, 0x06};
static constexpr uint8_t CENTER_CAPTURE_VAL[5] = {0x02, 0x03, 0x00, 0x05, 0x06};

static constexpr uint8_t DPAD_UP_N = 7;
static constexpr uint8_t DPAD_UP_IDX[7] = {6, 7, 8, 9, 10, 16, 17};
static constexpr uint8_t DPAD_UP_MASK[7] = {0x07, 0x70, 0x07, 0xd4, 0x40, 0x22, 0x0e};
static constexpr uint8_t DPAD_UP_VAL[7] = {0x03, 0x00, 0x04, 0x84, 0x40, 0x00, 0x02};

static constexpr uint8_t DPAD_DOWN_N = 4;
static constexpr uint8_t DPAD_DOWN_IDX[4] = {7, 10, 16, 17};
static constexpr uint8_t DPAD_DOWN_MASK[4] = {0xf0, 0x30, 0x86, 0x0e};
static constexpr uint8_t DPAD_DOWN_VAL[4] = {0x70, 0x20, 0x04, 0x0a};

static constexpr uint8_t DPAD_LEFT_N = 3;
static constexpr uint8_t DPAD_LEFT_IDX[3] = {7, 16, 17};
static constexpr uint8_t DPAD_LEFT_MASK[3] = {0x10, 0x20, 0x7d};
static constexpr uint8_t DPAD_LEFT_VAL[3] = {0x10, 0x00, 0x31};

static constexpr uint8_t DPAD_RIGHT_N = 5;
static constexpr uint8_t DPAD_RIGHT_IDX[5] = {4, 9, 10, 16, 17};
static constexpr uint8_t DPAD_RIGHT_MASK[5] = {0x02, 0x01, 0x30, 0x7a, 0x04};
static constexpr uint8_t DPAD_RIGHT_VAL[5] = {0x02, 0x01, 0x20, 0x0a, 0x04};

static constexpr uint8_t STICK_L3_N = 5;
static constexpr uint8_t STICK_L3_IDX[5] = {6, 7, 10, 16, 17};
static constexpr uint8_t STICK_L3_MASK[5] = {0x03, 0x70, 0x30, 0x3a, 0x07};
static constexpr uint8_t STICK_L3_VAL[5] = {0x02, 0x30, 0x10, 0x28, 0x06};

static constexpr uint8_t STICK_R3_N = 6;
static constexpr uint8_t STICK_R3_IDX[6] = {6, 7, 8, 9, 16, 17};
static constexpr uint8_t STICK_R3_MASK[6] = {0x3f, 0xa0, 0xf2, 0x07, 0x86, 0x75};
static constexpr uint8_t STICK_R3_VAL[6] = {0x14, 0x20, 0x82, 0x03, 0x82, 0x35};

} // namespace Switch2ProCapture
