#ifndef _SDK_CONFIG_H_
#define _SDK_CONFIG_H_

#include "Board/Config.h"

//
// Emulate "menuconfig"
//
#define CONFIG_BLUEPAD32_MAX_DEVICES MAX_GAMEPADS
#define CONFIG_BLUEPAD32_MAX_ALLOWLIST 4
#define CONFIG_BLUEPAD32_GAP_SECURITY 1
#define CONFIG_BLUEPAD32_ENABLE_BLE_BY_DEFAULT 1
// #define CONFIG_BLUEPAD32_ENABLE_VIRTUAL_DEVICE_BY_DEFAULT 1

#define CONFIG_BLUEPAD32_PLATFORM_CUSTOM
#define CONFIG_TARGET_PICO_W

// 2 == Info
#define CONFIG_BLUEPAD32_LOG_LEVEL 0

#endif //_SDK_CONFIG_H_