/* Maple Bus host. Ported from DreamPicoPort. */

#pragma once

#include "MaplePacket.hpp"
#include "maple_config.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include <cstdint>

/* Generated by pico_generate_pio_header */
#include "maple_in.pio.h"
#include "maple_out.pio.h"

class MapleBus {
public:
    enum class Phase : uint8_t {
        IDLE = 0,
        WRITE_IN_PROGRESS,
        WRITE_FAILED,
        WRITE_COMPLETE,
        WAITING_FOR_READ_START,
        READ_IN_PROGRESS,
        READ_FAILED,
        READ_COMPLETE,
    };
    enum class FailureReason : uint8_t {
        NONE = 0,
        CRC_INVALID,
        MISSING_DATA,
        BUFFER_OVERFLOW,
        TIMEOUT,
    };
    struct Status {
        Phase phase;
        FailureReason failureReason;
        const uint32_t* readBuffer;
        uint32_t readBufferLen;
        MaplePacket::ByteOrder rxByteOrder;
    };

    MapleBus(uint32_t pinA, int32_t dirPin = -1, bool dirOutHigh = true);

    bool write(const MaplePacket& packet, bool autostartRead,
               uint64_t readTimeoutUs = MAPLE_RESPONSE_TIMEOUT_US,
               MaplePacket::ByteOrder rxByteOrder = MaplePacket::ByteOrder::HOST);

    /** Start listening for an incoming packet (device mode). No write; use processEvents until READ_COMPLETE. */
    bool startRead(uint64_t readTimeoutUs = 0, MaplePacket::ByteOrder rxByteOrder = MaplePacket::ByteOrder::HOST);

    void writeIsr();
    void readIsr();

    Status processEvents(uint64_t currentTimeUs);

    bool isBusy() const { return mCurrentPhase != Phase::IDLE; }

private:
    bool lineCheck();
    void setDirection(bool output);

    const uint32_t mPinA;
    const uint32_t mPinB;
    const int32_t mDirPin;
    const bool mDirOutHigh;
    const uint32_t mMaskA;
    const uint32_t mMaskB;
    const uint32_t mMaskAB;
    const uint mOutOffset;
    const uint mInOffset;
    const uint mSmOut;
    const uint mSmIn;
    const int mDmaWriteChannel;
    const int mDmaReadChannel;

    volatile uint32_t mWriteBuffer[258];
    volatile uint32_t mReadBuffer[258];
    uint32_t mLastRead[256];

    Phase mCurrentPhase;
    bool mExpectingResponse;
    uint64_t mResponseTimeoutUs;
    MaplePacket::ByteOrder mRxByteOrder;
    uint64_t mProcKillTime;
    uint64_t mLastReceivedWordTimeUs;
    uint32_t mLastReadTransferCount;
};
